stages:
  - test
  - mirror

lint:
  image: node:latest
  stage: test
  script:
    - bash scripts/lint.sh

minify:
  image: node:latest
  stage: test
  script:
    - bash scripts/minify.sh

github:
  image: debian:stable
  stage: mirror
  only:
    - master
  script:
    - bash scripts/github.sh
