stages:
  - test
  - mirror
  - deploy

lint:
  image: node:latest
  stage: test
  script:
    - bash scripts/lint.sh

minify:
  image: node:latest
  stage: test
  script:
    - bash scripts/minify.sh

pages:
  image: ruby:2.6
  stage: deploy
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  script:
    - bash startup.sh --deploy
  artifacts:
    paths:
      - public
  only:
    - master
